name: Deploy React App to S3

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' 

    - name: Install dependencies
      run: npm ci

    - name: Build React app
      run: npm run build
      env:
        # Add your environment variables here
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        REACT_APP_OTHER_VAR: ${{ secrets.REACT_APP_OTHER_VAR }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # replace with your AWS region

    - name: Deploy to S3
      run: |
        aws s3 sync build/ s3://react-weather-todo-training --delete
